version: "3.9"

services:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
   
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: phila1234
      MYSQL_ROOT_PASSWORD: wordpress
  
  wp:
    depends_on:
      - db
    image: johncajigas/wp-image
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: phila1234
      WORDPRESS_DB_NAME: wordpress
      
  wpcli:
    profiles:
      - install
    image: wordpress:cli-2.6.0-php8.1
    depends_on:
      - wp
    volumes:
      - ./install-activate.sh:/install-activate.sh
      - wp_data:/var/www/html
      - db_data:/var/lib/mysql
    user: "33"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: phila1234
      WORDPRESS_DB_NAME: wordpress
    command: /install-activate.sh

volumes:
  db_data: {}
  wp_data: {}